arguments:
- no_flip: 1
- fsdp: 1
- fsdp_text_encoder: 1
- img_size: 640
- secondary_img_size: 512
- txt_size: 256
- vid_size: '81:16'
- fps_cond: 1
- channel_size: 48
- patch_size: 1
- channels: 3072
- top_block_channels: 4096
- blocks: 6
- layers_per_block: 2 2 2 2 2 24
- noise_std: 0.5
- batch_size: 192
- secondary_batch_size: 1536
- secondary_ratio: 0.2
- lr: 5e-5
- min_lr: 1e-6
- nvp: 1
- rope: 1
- adaln: 0
- sos: 1
- seq_order: L2R
- pt_seq_len: 32
- wds: 1
- mix_aspect: 1
- use_softplus: 1
- cond_top_only: 1
- use_final_norm: 1
- learnable_self_denoiser: 1
- conditional_denoiser: 1
- denoiser_window: 10
- cond_noise_level: 1
- temporal_causal: 2
- shallow_block_local: 1
- gradient_checkpoint: 1
- gradient_checkpoint_mlp: 1
- vae: Wan-AI/Wan2.2-TI2V-5B-Diffusers:0.6
- finetuned_vae: none
- text: google/flan-t5-xl
- cfg: 2.5
- drop_label: 0.1
- drop_image: 0.25
- loss_scaling: 1
- grad_clip: 1
- grad_skip: 1
- sample_freq: 100000
- soft_clip: 4
